### ISSUE TITLE
Change cooldown dialog from seconds to hh:mm

### ISSUE THREAD

**Issue by tofumarinado** [myrthe-vt/HCVSG#5]
It would be cool to change the cooldown dialog the bot gives as feedback after a user tries to repeat an action before the cooldown resets.

Right now, it's displayed as such:
```
> .bugs

> You cannot catch a bug yet! Please wait 1758 seconds.
```

It would be nice if it were displayed like this:

```
> .bugs

> You cannot catch a bug yet! Please wait 3 hours, 12 minutes.
```

**Comment by myrthe-vt** [comment]
Solved it!
